### ISSUE TITLE
Fix deploy-artifact message

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-stack-manager-messenger#2]
`deploy-artifact` message is currently incomplete https://github.com/shinesolutions/aem-stack-manager-messenger/blob/master/files/deploy-artifact.txt

It's missing package group, name, and version, along with replicate, activate, and force values.

**Comment by andy-wang-haibo** [comment]
deploy-artifact message has been fixed in the dev branch and have been tested.
