### ISSUE TITLE
Display action/event log message

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-stack-manager-messenger#6]
Another step to be added to the playbook is one that downloads the log from S3 to the workspace, and then optionally display the log output (e.g. if the result is a failure, display the log output, if it's a success, up to user to check the log file in the filesystem).

This will help the user with troubleshooting the result of the action.

**Comment by mbloch1986** [comment]
To Display action/event log message probably they need to store in the S3 Stack folder.

**Comment by mbloch1986** [comment]
At the moment they are stored under S3Bucket/SSMOutput and should be in S3Bucket/Stack/SSMOutput

**Comment by mbloch1986** [comment]
Lambda configuration file is now created with the path for the SSMOutput under the Stack-Manager folder.

See https://github.com/shinesolutions/aem-aws-stack-builder/pull/94
